### ISSUE TITLE
Inaccurate error log message "Fatal error: existing private key lock file"

### ISSUE THREAD

**Issue by jmc000** [ObolNetwork/charon#2385] opened 2023-06-30 19:52 UTC
# 🐞 Bug Report

I came across errors when running `charon run` command where logs weren't accurate which can be confusing when debugging.

They are 2 case were I got this inaccurate log:

### Description

I launched my `charon run` command and get these logs below:

```bash
charon[55705]: 00:25:32.440 INFO app-start  Charon starting                          {"version": "v0.16-rc", "git_commit_hash": "05f8a64", "git_commit_time": "2023-06-16T11:51:15Z"}
charon[55705]: 00:25:32.441 ERRO cmd        Fatal error: existing private key lock file found, another charon instance may be running on your machine {"path": "/home/obol/.charon_0/charon-enr-private-key.lock", "command": "charon run"}
charon[55705]:         app/privkeylock/privkeylock.go:36 .New
charon[55705]:         app/app.go:137 .Run
charon[55705]:         cmd/run.go:37 .func1
charon[55705]:         cmd/cmd.go:75 .func1
charon[55705]:         main.go:19 .main
```

But the error wasn't related to `charon-enr-private-key.lock` file. 

The error appears to be because I setted a bad value to `--p2p-tcp-address` argument: `--p2p-tcp-address 10.2.0.9,10.2.0.7,10.2.0.10` instead of `--p2p-tcp-address 10.2.0.9:3610,10.2.0.7:3611,10.2.0.10:3612`

I also had the same error logs when I launched the charon without the `$HOME/.charon/cluster-lock.json` file.

## 🔬 Minimal Reproduction

1. Launch a charon node with a p2p-address without the ports: `charon run --p2p-tcp-address 10.2.0.9,10.2.0.7,10.2.0.10 ...`

OR

2. Launch a charon node without the `$HOME/.charon/cluster-lock.json` file

## 🔥 Error

In both cas described logs should be related to the error, here it isn't and make it more complicated to debug

## 🌍  Your Environment

Linux distro: `ubuntu 20.04 LTS`
Charon version: `v0.16-rc [git_commit_hash=05f8a64,git_commit_time=2023-06-16T11:51:15Z]`

**Comment by gsora** [comment] 2023-07-05 15:40
Was `--private-key-file-lock` enabled on the CLI flags list?

**Comment by jmc000** [comment] 2023-07-06 14:55
yes

```
/home/obol/bin/charon run \
  --beacon-node-endpoints http://W.X.Y.Z:5052 \
  --validator-api-address 127.0.0.1:3600 \
  --p2p-allowlist 10.2.0.0/16 \
  --p2p-external-ip 10.2.0.9 \
  --p2p-tcp-address 0.0.0.0:3610 \
  --p2p-relays https://0.relay.obol.tech/ \
  --monitoring-address 0.0.0.0:3620 \
  --private-key-file /home/obol/.charon/charon-enr-private-key \
  --private-key-file-lock \
  --lock-file /home/obol/.charon/cluster-lock.json
```

**Comment by gsora** [comment] 2023-07-06 15:35
Did you kill the charon binary with SIGKILL or similar, or have more than one charon instance running on that machine?

**Comment by jmc000** [comment] 2023-07-06 20:38
It was during a host migration from VM A (with public IP) to VM B (in a VPC). When I stopped the daemon on VM A doing `systemctl stop charon` the `charon-enr-private-key.lock` wasn't here anymore so the stop was smooth.

When migrating to VM B, I got this error on a host where no Charon client was running and on which none had ever runned before.

**Comment by gsora** [comment] 2023-07-12 09:10
Ok so gave this issue a full round of review, including going through the private key lock feature codebase to see if there was something wrong.

I can confidently say the feature is working as intended, and wasn't able to reproduce your issue locally.

I see that in your error message you're referring to `/home/obol/.charon_0/`, while in the `run` command you mentioned later in the conversation, `--private-key-file` was set to `/home/obol/.charon`.

I wonder if there was maybe some mishap during the node migration?

Also apparently you're using a release candidate release, could you check if it reproduces with the latest stable release?

**Comment by jmc000** [comment] 2023-07-18 15:35
yes `/home/obol/.charon_0/` was on the hold host where `/home/obol/.charon/` was on the new one, I was careful it don't think it's related to it - ok strange / too bad that you can't reproduce it

for the release I use the `v0.16.0` tag (& building it with `go build` command), which one is the latest release if not this one?

**Comment by corverroos** [comment] 2023-07-25 17:08
Removed the bug label as this doesn't seem to be a bug

**Comment by gsora** [comment] 2023-07-27 09:48
> for the release I use the v0.16.0 tag (& building it with go build command), which one is the latest release if not this one?

Yes it's the latest one, was asking because i noticed the `-rc` suffix in the version report.

I'm going to close this issue since we're not able to reproduce it, feel free to reopen it if happens again!

**Closed by gsora** 2023-07-27 09:48 UTC
Labels: protocol
