### ISSUE TITLE
Beaconmock Lighthouse block proposal issue

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#860] opened 2022-07-26 14:16 UTC
## Problem to be solved

Lighthouse is failing to propose blocks produced by the beaconmock in simnet.

```
vc1-lighthouse_1  | Jul 26 12:45:52.582 CRIT Error whilst producing block            message: All endpoints failed http://node1:3600/ => RequestFailed("Error from beacon node when producing block: Reqwest(reqwest::Error { kind: Decode, source: Error(\"data did not match any variant of untagged enum BeaconBlock\", line: 1, column: 2621) })"), service: block
```

This is both older `v2.1.5` and new `v2.4.0` versions of Lighthouse

## Proposed solution

It seems like an issue with block formatting produced by beaconmock. Investigate and fix.

**Comment by gsora** [comment] 2023-01-31 09:52
Gave this issue a round of research:

 - it's still happening with the latest stable Lighthouse release, 3.4.0
 - issue seems to be related to HTTP keep-alive
 - @corverroos pointed out we weren't closing the HTTP request body after reading it, which might be related to keep-alive: no dice, still happens after fixing that
 - happens on v2.4.0 even after fixing the body closing issue
 - stress-testing with [vegeta](https://github.com/tsenart/vegeta) didn't show any sign of distress: keep-alive is used correctly and handled as it should

**Comment by gsora** [comment] 2023-01-31 10:44
I wrote a dumb HTTP stress tester using the same underlying library as lighthouse: 

```rust
use std::time::Duration;

use reqwest::{ClientBuilder, StatusCode};

#[derive(Debug)]
enum Error {
    Reqwest(reqwest::Error),
    MissingURL,
}

impl From<reqwest::Error> for Error {
    fn from(e: reqwest::Error) -> Self {
        Self::Reqwest(e)
    }
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    // Some simple CLI args requirements...
    let url = match std::env::args().nth(1) {
        Some(url) => url,
        None => return Err(Error::MissingURL),
    };

    eprintln!("Fetching {:?}...", url);

    let client = ClientBuilder::new()
        .tcp_keepalive(Duration::from_secs(1))
        .build()
        .unwrap();

    for idx in 0..1_000_000 {
        let res = client.post(url.clone()).send().await?;

        if res.status() != StatusCode::OK {
            println!("status code not OK!: {}", res.status())
        }

        println!("Done call #{}...", idx);
    }

    Ok(())
}
```

The results are underwhelming: even when ran inside the same `compose` cluster, I'm not able to reproduce the behavior we're observing.

We could add a configuration flag in Charon (`CHARON_DISABLE_HTTPKEEPALIVE`) that disables HTTP keep-alive when needed, and update `compose` to generate `docker-compose.yaml` files with that env var on.

I recognize this is a workaround rather than a fix, and I'm not 100% in favor of doing it either, but it effectively frees us of this problem and allows us to keep working on other issues.

**Comment by gsora** [comment] 2023-01-31 11:38
Just reproduced with the Rust stresser: 

```
Error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(3600), path: "/eth/v1/validator/prepare_beacon_proposer", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) })
```

I'm tempted to both implement the workaround as described earlier *and* report this bug to lighthouse.

**Comment by gsora** [comment] 2023-01-31 13:57
Closing in favor of #1736, since the original error cannot be reproduced anymore.

**Closed by gsora** 2023-01-31 13:57 UTC
Labels: bug, protocol
