### ISSUE TITLE
data race in p2p package

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2784] opened 2024-01-12 11:29 UTC
# 🐞 Bug Report

### Description

A data race condition was observed in a github job running on a PR: https://github.com/ObolNetwork/charon/actions/runs/7464121777/job/20415456429?pr=2777

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

See the logs here: https://github.com/ObolNetwork/charon/actions/runs/7464121777/job/20415456429?pr=2777

## 🔥 Error

```
==================
WARNING: DATA RACE
Write at 0x00c007869a30 by goroutine 149088:
  github.com/obolnetwork/charon/p2p.(*Sender).addResult()
      /home/runner/work/charon/charon/p2p/sender.go:67 +0x19c
  github.com/obolnetwork/charon/p2p.(*Sender).SendAsync.func1()
      /home/runner/work/charon/charon/p2p/sender.go:117 +0x27c

Previous write at 0x00c007869a30 by goroutine 149081:
  github.com/obolnetwork/charon/p2p.(*Sender).addResult()
      /home/runner/work/charon/charon/p2p/sender.go:67 +0x19c
  github.com/obolnetwork/charon/p2p.(*Sender).SendAsync.func1()
      /home/runner/work/charon/charon/p2p/sender.go:117 +0x27c

Goroutine 149088 (running) created at:
  github.com/obolnetwork/charon/p2p.(*Sender).SendAsync()
      /home/runner/work/charon/charon/p2p/sender.go:110 +0x288
  github.com/obolnetwork/charon/core/consensus.(*transport).Broadcast()
      /home/runner/work/charon/charon/core/consensus/transport.go:131 +0xdd6
  github.com/obolnetwork/charon/core/consensus.(*transport).Broadcast-fm()
      <autogenerated>:1 +0x16b
  github.com/obolnetwork/charon/core/qbft.Run[go.shape.struct { Slot uint64; Type github.com/obolnetwork/charon/core.DutyType },go.shape.[32]uint8].func2()
      /home/runner/work/charon/charon/core/qbft/qbft.go:198 +0x1c2
  github.com/obolnetwork/charon/core/qbft.Run[go.shape.struct { Slot uint64; Type github.com/obolnetwork/charon/core.DutyType },go.shape.[32]uint8]()
      /home/runner/work/charon/charon/core/qbft/qbft.go:321 +0x16b4
  github.com/obolnetwork/charon/core/consensus.(*Component).runInstance()
      /home/runner/work/charon/charon/core/consensus/component.go:469 +0xe48
  github.com/obolnetwork/charon/core/consensus.(*Component).propose()
      /home/runner/work/charon/charon/core/consensus/component.go:375 +0x6a4
  github.com/obolnetwork/charon/core/consensus.(*Component).ProposePriority()
      /home/runner/work/charon/charon/core/consensus/component.go:327 +0x74
  github.com/obolnetwork/charon/core/priority.startConsensus.func1()
      /home/runner/work/charon/charon/core/priority/prioritiser.go:369 +0x9d

Goroutine 149081 (running) created at:
  github.com/obolnetwork/charon/p2p.(*Sender).SendAsync()
      /home/runner/work/charon/charon/p2p/sender.go:110 +0x288
  github.com/obolnetwork/charon/core/consensus.(*transport).Broadcast()
      /home/runner/work/charon/charon/core/consensus/transport.go:131 +0xdd6
  github.com/obolnetwork/charon/core/consensus.(*transport).Broadcast-fm()
      <autogenerated>:1 +0x16b
  github.com/obolnetwork/charon/core/qbft.Run[go.shape.struct { Slot uint64; Type github.com/obolnetwork/charon/core.DutyType },go.shape.[32]uint8].func2()
      /home/runner/work/charon/charon/core/qbft/qbft.go:198 +0x1c2
  github.com/obolnetwork/charon/core/qbft.Run[go.shape.struct { Slot uint64; Type github.com/obolnetwork/charon/core.DutyType },go.shape.[32]uint8]()
      /home/runner/work/charon/charon/core/qbft/qbft.go:284 +0x1865
  github.com/obolnetwork/charon/core/consensus.(*Component).runInstance()
      /home/runner/work/charon/charon/core/consensus/component.go:469 +0xe48
  github.com/obolnetwork/charon/core/consensus.(*Component).propose()
      /home/runner/work/charon/charon/core/consensus/component.go:375 +0x6a4
  github.com/obolnetwork/charon/core/consensus.(*Component).ProposePriority()
      /home/runner/work/charon/charon/core/consensus/component.go:327 +0x74
  github.com/obolnetwork/charon/core/priority.startConsensus.func1()
      /home/runner/work/charon/charon/core/priority/prioritiser.go:369 +0x9d
==================
```

## 🌍  Your Environment

None

**What version of Charon are you running? (Which release)**

Latest

**Anything else relevant (validator index / public key)?**

**Comment by dB2510** [comment] 2024-01-31 15:25
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2784?planning-poker) with Zenhub @dB2510 @gsora @pinebit @xenowits

**Comment by gsora** [comment] 2024-02-08 11:58
Duplicate of https://github.com/ObolNetwork/charon/issues/2763

**Closed** 2024-02-13 09:17 UTC
Labels: bug, protocol
