### ISSUE TITLE
Missed attestation in a cluster

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2390] opened 2023-07-03 10:16 UTC
# 🎯 Problem to be solved
A cluster missed an attestation on the 3rd of July around 11AM UTC+1. Their latency is super low and consensus rounds too. One peer was offline but the cluster is a 5 out of 7.  
https://grafana.monitoring.gcp.obol.tech/d/d6qujIJVk/charon-overview-v3?orgId=1&var-cluster_name=obol-alpha&var-cluster_hash=fd28f1f&var-cluster_peer=homely-rope&var-job=charon&var-peer=All&var-interval=$__auto_interval_interval&var-duty=All&var-cluster_network=goerli

that attestation was broadcasted but never included on chain. Around that time there was an attestation inclusion delay of 5 slots, `homely-rope` beacon node score was 58% during that time frame.

# 🛠️ Proposed solution

# 🧪 Tests

**Comment by corverroos** [comment] 2023-07-12 13:55
Attestations are not guaranteed to be included on-chain even if broadcasted by charon early enough. The process of getting such an attestation included on-chain includes multiple steps that we are not in control of and that can fail. It is expected that roughly 1%-5% of braodcasted attestations will not be included on-chain. 

Closing as "not a bug"

**Closed by corverroos** 2023-07-12 13:55 UTC
