### ISSUE TITLE
Stafi Integration

### ISSUE THREAD

**Issue by samparsky** [ObolNetwork/charon#2632] opened 2023-10-09 15:25 UTC

**Comment by dB2510** [comment] 2023-10-11 11:22
Hey @samparsky 👋 
Is this ticket related to charon?

**Comment by dB2510** [comment] 2023-10-11 11:23
Also this is duplicate of #2631

**Comment by dB2510** [comment] 2023-10-13 07:54
closing this as this is duplicate of #2631

**Closed by dB2510** 2023-10-13 07:54 UTC
Labels: protocol
